export const JOB_ICON_IDS_BY_LABEL = Object.freeze({
  'abyss chaser': 4260,
  acolyte: 4,
  alitea: 4355,
  'arc mage': 4255,
  'arch bishop': 4063,
  'arch mage': 4255,
  archer: 3,
  'assassin cross': 4013,
  biolo: 4259,
  cardinal: 4256,
  champion: 4016,
  clown: 4020,
  creator: 4019,
  'dragon knight': 4252,
  druid: 4351,
  'elemental master': 4261,
  genetic: 4078,
  'glt. cross': 4065,
  gunslinger: 24,
  gypsy: 4021,
  'high priest': 4009,
  'high wizard': 4010,
  'hyper novice': 4307,
  'imperial guard': 4258,
  inquisitor: 4262,
  kagerou: 4211,
  karnos: 4353,
  'lord knight': 4008,
  magician: 2,
  mechanic: 4064,
  meister: 4253,
  merchant: 5,
  minstrel: 4075,
  'night watch': 4306,
  ninja: 25,
  novice: 0,
  oboro: 4212,
  paladin: 4015,
  professor: 4017,
  ranger: 4062,
  rebellion: 4215,
  'royal guard': 4073,
  'rune knight': 4060,
  'shadow chaser': 4079,
  'shadow cross': 4254,
  shinkiro: 4304,
  shiranui: 4305,
  'sky emperor': 4302,
  sniper: 4012,
  sorcerer: 4074,
  'soul ascetic': 4303,
  'soul linker': 4049,
  'soul reaper': 4240,
  'spirit handler': 4308,
  stalker: 4018,
  'star emperor': 4239,
  'star gladiator': 4047,
  summoner: 4218,
  'super novice': 23,
  'super novice 2': 4190,
  sura: 4077,
  swordman: 1,
  'taekwon boy': 4046,
  thief: 6,
  troubadour: 4263,
  trouvere: 4264,
  wanderer: 4076,
  warlock: 4061,
  whitesmith: 4011,
  'wind hawk': 4257,
  windhawk: 4257,
})

export const BROWIKI_CLASS_ICON_FILES_BY_LABEL = Object.freeze({
  'abyss chaser': 'Mandraquespartyicn.png',
  acolyte: 'Noviçospartyicn.png',
  alitea: 'Aliteapartyicn.png',
  'arc mage': 'Arquimagospartyicn.png',
  'arch bishop': 'Arcebispospartyicn.png',
  'arch mage': 'Arquimagospartyicn.png',
  archer: 'Arqueirospartyicn.png',
  'assassin cross': 'Algozespartyicn.png',
  biolo: 'Cientistaspartyicn.png',
  cardinal: 'Cardeaispartyicn.png',
  champion: 'Mestrespartyicn.png',
  clown: 'Menestréispartyicn.png',
  creator: 'Criadorespartyicn.png',
  'dragon knight': 'Cavaleiros Draconianospartyicn.png',
  druid: 'Druidaspartyicn.png',
  'elemental master': 'Elementalistaspartyicn.png',
  genetic: 'Bioquímicospartyicn.png',
  'glt. cross': 'Sicáriospartyicn.png',
  gunslinger: 'Justiceirospartyicn.png',
  gypsy: 'Ciganaspartyicn.png',
  'high priest': 'Sumo Sacerdotespartyicn.png',
  'high wizard': 'Bruxospartyicn.png',
  'hyper novice': 'Hiperaprendizespartyicn.png',
  'imperial guard': 'Guardiões Imperiaispartyicn.png',
  inquisitor: 'Inquisidorespartyicn.png',
  kagerou: 'Kageroupartyicn.png',
  karnos: 'Karnospartyicn.png',
  'lord knight': 'Lordespartyicn.png',
  magician: 'Magospartyicn.png',
  mechanic: 'Mecânicospartyicn.png',
  meister: 'Engenheirospartyicn.png',
  merchant: 'Mercadorespartyicn.png',
  minstrel: 'Menestréispartyicn.png',
  'night watch': 'Guerrilheirospartyicn.png',
  ninja: 'Ninjaspartyicn.png',
  novice: 'Aprendizespartyicn.png',
  oboro: 'Oboropartyicn.png',
  paladin: 'Paladinospartyicn.png',
  professor: 'Professorespartyicn.png',
  ranger: 'Sentinelaspartyicn.png',
  rebellion: 'Insurgentespartyicn.png',
  'royal guard': 'Guardiões Reaispartyicn.png',
  'rune knight': 'Cavaleiros Rúnicospartyicn.png',
  'shadow chaser': 'Renegadospartyicn.png',
  'shadow cross': 'Executorespartyicn.png',
  shinkiro: 'Shinkiropartyicn.png',
  shiranui: 'Shiranuipartyicn.png',
  'sky emperor': 'Mestres Celestiaispartyicn.png',
  sniper: 'Atiradores de Elitepartyicn.png',
  sorcerer: 'Feiticeirospartyicn.png',
  'soul ascetic': 'Ascetas das Almaspartyicn.png',
  'soul linker': 'Espiritualistaspartyicn.png',
  'soul reaper': 'Ceifadores de Almaspartyicn.png',
  'spirit handler': 'Animistaspartyicn.png',
  stalker: 'Desordeirospartyicn.png',
  'star emperor': 'Mestres Estelarespartyicn.png',
  'star gladiator': 'Mestres Taekwonspartyicn.png',
  summoner: 'Invocadorespartyicn.png',
  'super novice': 'Superaprendizespartyicn.png',
  'super novice 2': 'Superaprendizes EXpartyicn.png',
  sura: 'Shuraspartyicn.png',
  swordman: 'Espadachinspartyicn.png',
  'taekwon boy': 'Taekwonspartyicn.png',
  thief: 'Gatunospartyicn.png',
  troubadour: 'Trovadorespartyicn.png',
  trouvere: 'Divaspartyicn.png',
  wanderer: 'Musaspartyicn.png',
  warlock: 'Arcanospartyicn.png',
  whitesmith: 'Mestres-Ferreirospartyicn.png',
  'wind hawk': 'Falcões do Ventopartyicn.png',
  windhawk: 'Falcões do Ventopartyicn.png',
})

export function jobIconAssetUrl(jobIconId) {
  return `assets/divine-pride/job-icons/${jobIconId}.png`
}

export function jobIconIdFromPath(path) {
  const match = String(path ?? '').match(/\/(\d+)\.png$/)
  return match ? Number(match[1]) : undefined
}

export function jobIconUrlForLabelAndPath(label, path) {
  const normalizedLabel = normalizeJobLabel(label)
  const jobIconId = jobIconIdFromPath(path) ?? JOB_ICON_IDS_BY_LABEL[normalizedLabel]
  return jobIconId !== undefined ? jobIconAssetUrl(jobIconId) : ''
}

export function knownJobIconAssets() {
  return Object.entries(BROWIKI_CLASS_ICON_FILES_BY_LABEL)
    .map(([label, browikiFileName]) => ({
      label,
      browikiFileName,
      jobIconId: JOB_ICON_IDS_BY_LABEL[label],
    }))
    .filter((asset) => asset.jobIconId !== undefined)
}

export function normalizeJobLabel(label) {
  return String(label ?? '').trim().replace(/\s+/g, ' ').toLowerCase()
}